[package]
name = "anyxml-base64"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "simple Base64 library for XML"
keywords = ["base64", "xml"]
rust-version.workspace = true

[dependencies]
